### ISSUE TITLE
Upload to supermarket?

### ISSUE THREAD

**Issue by nozpheratu** [dev-sec/chef-nginx-hardening#38]
Any plans to upload this to Chef supermarket?

**Comment by atomic111** [comment]
sorry for the late response @nozpheratu. not a bad idea, i will discuss this with @arlimus @chris-rock and come back to you

**Comment by enzor** [comment]
Hi!
Is this possible to upload this cookbook to the supermarket, to avoid the inclusion of this cookbook in every berksfile we have?

**Comment by chris-rock** [comment]
Its available in supermarket now: https://supermarket.chef.io/cookbooks/nginx-hardening
