### ISSUE TITLE
Nginx fails with "No such file or directory /etc/nginx/dh2048.pem"

### ISSUE THREAD

**Issue by vpal** [dev-sec/chef-nginx-hardening#45]
It seems like the `/etc/nginx/conf.d/90.hardening.conf` is generated and after that Nginx is restarted.
This file contains the `ssl_dhparam /etc/nginx/dh2048.pem;` directive, but `execute 'generate_dh_group'` is at the end of the recipe so Nginx fails to restart...

Moving the execute resource before the template resource helps.

**Comment by atomic111** [comment]
@vpal thank you for reporting this. can you please create a pr for this

**Comment by onwsk8r** [comment]
Fixed in #50
